project:
  type: website
  output-dir: .

website:
  title: "Cole J. Harvey, PhD"
  navbar: 
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Research"
        href: research.qmd
      - text: "Book project"
        href: book.qmd
  page-footer:
    center: "© 2025 Cole Harvey"
format:
  html:
    theme: sandstone
    css: styles.css
    include-before-body:
      text: |
    <script data-goatcounter="https://colejharvey.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>
